sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t keenanchan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true keenanchan/react-test npm test

after_success:
  - docker build -t keenanchan/multi-client ./client
  - docker build -t keenanchan/multi-nginx ./nginx
  - docker build -t keenanchan/multi-server ./server
  - docker build -t keenanchan/multi-worker ./worker
  # take images, push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push keenanchan/multi-client
  - docker push keenanchan/multi-nginx
  - docker push keenanchan/multi-server
  - docker push keenanchan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'udemy-docker-multi'
  env: 'Udemydockermulti-env'
  bucket_name: 'elasticbeanstalk-us-east-1-175412969001'
  bucket_path: 'udemy-docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
