# Production docker-compose.yml, used by AWS EB
# Postgres and Redis containers will be replaced by AWS-hosted services
version: '3'
services:
  nginx:
    image: "keenanchan/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  api:
    image: "keenanchan/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: "keenanchan/multi-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "keenanchan/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
